repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.8
  hooks:
    - id: ruff
      args: [ --select, I, --fix ]
    - id: ruff-format

# Custom hook to upgrade pip
- repo: local
  hooks:
    - id: upgrade-pip
      name: Upgrade pip
      entry: ./upgrade_pip.sh
      language: script
      files: ^requirements.txt$
