name: recommend2024
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - torch: "~=2.0.1"
  - smartdict: "~=0.0.3"
  - pandas: "~=2.2.2"
  - scikit-learn: "~=1.4.0"
  - termcolor: ""
  - refconfig: "~=0.0.2"
  - oba: "~=0.0.6"
  - numpy: "~=1.24.0"
  - UniTok: "~=3.4.5"
  - transformers: "~=4.30.2"
  - tqdm: "~=4.64.1"
  - peft: "~=0.3.0"
  - pigmento: "~=0.1.3"
  - nltk: "~=3.7"
  - Pillow: "~=9.2.0"
  - requests: ""
  - openai: ""
  - PyYAML: ""
  - pre-commit: ""
  - ruff: ""
  - pytest: ""
  - tensorflow: ">=2.12.0, <2.16.0"
  - polars: "==0.20.8"
  - pyyaml: "==6.0.1"