# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip==24.1.1
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev meson cmake
    - name: Install Python dependencies
      run: pip install --only-binary :all: numpy scipy
    - run: pip install -r requirements.txt
    - name: Lint with Ruff
      run: |
        ruff check --output-format=github .